import { Blog } from "@/types";

export const blogs: Blog[] = [
  {
    title: 'Getting Started with Next.js 14',
    excerpt: 'Learn about the new features and improvements in Next.js 14.',
    date: '2024-03-15',
    readTime: '5 min read',
    slug: 'getting-started-with-nextjs-14',
  },
  {
    title: 'Mastering TypeScript for React',
    excerpt: 'A comprehensive guide to using TypeScript with React applications.',
    date: '2024-03-10',
    readTime: '8 min read',
    slug: 'mastering-typescript-for-react',
  },
  {
    title: 'Building Responsive Layouts with Tailwind CSS',
    excerpt: 'Tips and tricks for creating responsive designs using Tailwind CSS.',
    date: '2024-03-05',
    readTime: '6 min read',
    slug: 'building-responsive-layouts-with-tailwind-css',
  },
  {
    title: 'Understanding React Hooks',
    excerpt: 'A deep dive into React Hooks and how to use them effectively.',
    date: '2024-03-01',
    readTime: '7 min read',
    slug: 'understanding-react-hooks',
  },
  {
    title: 'Deploying Next.js Applications on Vercel',
    excerpt: 'Step-by-step guide to deploying your Next.js applications on Vercel.',
    date: '2024-02-25',
    readTime: '4 min read',
    slug: 'deploying-nextjs-applications-on-vercel',
  },
  {
    title: 'Building a RESTful API with Node.js and Express',
    excerpt: 'Learn how to create a RESTful API using Node.js and Express.',
    date: '2024-02-20',
    readTime: '10 min read',
    slug: 'building-a-restful-api-with-nodejs-and-express',
  },
  // --- AI/ML Blogs ---
  {
    title: 'Introduction to Machine Learning',
    excerpt: 'Understand the basics of machine learning and its applications.',
    date: '2024-03-18',
    readTime: '8 min read',
    slug: 'introduction-to-machine-learning',
  },
  {
    title: 'Deep Learning with Python and TensorFlow',
    excerpt: 'A hands-on guide to building deep learning models using TensorFlow.',
    date: '2024-03-12',
    readTime: '12 min read',
    slug: 'deep-learning-with-python-and-tensorflow',
  },
  {
    title: 'Natural Language Processing with Python',
    excerpt: 'Learn NLP techniques and build chatbots and text analysis tools.',
    date: '2024-03-08',
    readTime: '10 min read',
    slug: 'natural-language-processing-with-python',
  },
  {
    title: 'Computer Vision Basics with OpenCV',
    excerpt: 'Implement image and video processing using OpenCV.',
    date: '2024-03-04',
    readTime: '9 min read',
    slug: 'computer-vision-basics-with-opencv',
  },
  {
    title: 'AI Model Deployment with Flask',
    excerpt: 'Learn to deploy machine learning models as web APIs using Flask.',
    date: '2024-03-01',
    readTime: '8 min read',
    slug: 'ai-model-deployment-with-flask',
  },
  // --- Spring Boot Blogs ---
  {
    title: 'Building REST APIs with Spring Boot',
    excerpt: 'Step-by-step tutorial for creating RESTful APIs using Spring Boot.',
    date: '2024-03-08',
    readTime: '9 min read',
    slug: 'building-rest-apis-with-spring-boot',
  },
  {
    title: 'Spring Boot Security Essentials',
    excerpt: 'Learn how to secure your Spring Boot applications effectively.',
    date: '2024-03-03',
    readTime: '7 min read',
    slug: 'spring-boot-security-essentials',
  },
  {
    title: 'Spring Boot Microservices Architecture',
    excerpt: 'Design and implement microservices using Spring Boot.',
    date: '2024-02-28',
    readTime: '10 min read',
    slug: 'spring-boot-microservices-architecture',
  },
  {
    title: 'Spring Boot with JPA & Hibernate',
    excerpt: 'Learn how to integrate Spring Boot with JPA and Hibernate.',
    date: '2024-02-25',
    readTime: '9 min read',
    slug: 'spring-boot-with-jpa-and-hibernate',
  },
  // --- Database Blogs ---
  {
    title: 'Getting Started with MySQL',
    excerpt: 'Learn how to set up and use MySQL for your applications.',
    date: '2024-02-28',
    readTime: '6 min read',
    slug: 'getting-started-with-mysql',
  },
  {
    title: 'Mastering MongoDB for Beginners',
    excerpt: 'A practical guide to using MongoDB in modern applications.',
    date: '2024-02-22',
    readTime: '7 min read',
    slug: 'mastering-mongodb-for-beginners',
  },
  {
    title: 'PostgreSQL Advanced Features',
    excerpt: 'Explore advanced features and best practices of PostgreSQL.',
    date: '2024-02-18',
    readTime: '9 min read',
    slug: 'postgresql-advanced-features',
  },
  {
    title: 'Database Indexing Explained',
    excerpt: 'Learn how indexing improves query performance in SQL databases.',
    date: '2024-02-14',
    readTime: '6 min read',
    slug: 'database-indexing-explained',
  },
  {
    title: 'SQL Joins Made Easy',
    excerpt: 'Understand INNER, LEFT, RIGHT, and FULL OUTER joins with examples.',
    date: '2024-02-10',
    readTime: '8 min read',
    slug: 'sql-joins-made-easy',
  },
  {
    title: 'MongoDB Replication & Sharding',
    excerpt: 'Learn about MongoDB replication, high availability, and sharding.',
    date: '2024-02-08',
    readTime: '10 min read',
    slug: 'mongodb-replication-and-sharding',
  },
  // --- Linux Blogs ---
  {
    title: 'Linux Basics for Developers',
    excerpt: 'Essential Linux commands and tools every developer should know.',
    date: '2024-02-15',
    readTime: '5 min read',
    slug: 'linux-basics-for-developers',
  },
  {
    title: 'Setting Up Development Environment on Linux',
    excerpt: 'A guide to setting up Java, Python, and Node.js on Linux.',
    date: '2024-02-12',
    readTime: '6 min read',
    slug: 'setting-up-development-environment-on-linux',
  },
  {
    title: 'Linux Shell Scripting for Automation',
    excerpt: 'Automate repetitive tasks using Bash shell scripting.',
    date: '2024-02-08',
    readTime: '7 min read',
    slug: 'linux-shell-scripting-for-automation',
  },
  {
    title: 'Top Linux Tools for Developers',
    excerpt: 'A list of essential Linux tools and utilities for developers.',
    date: '2024-02-05',
    readTime: '6 min read',
    slug: 'top-linux-tools-for-developers',
  },
  // --- Cloud / DevOps Related ---
  {
    title: 'Deploying Applications on AWS',
    excerpt: 'Learn how to deploy web applications on AWS EC2 and S3.',
    date: '2024-02-01',
    readTime: '9 min read',
    slug: 'deploying-applications-on-aws',
  },
  {
    title: 'Introduction to Docker for Developers',
    excerpt: 'Containerize your applications using Docker and Docker Compose.',
    date: '2024-01-28',
    readTime: '8 min read',
    slug: 'introduction-to-docker-for-developers',
  },
  {
    title: 'CI/CD Pipelines with GitHub Actions',
    excerpt: 'Automate build, test, and deployment with GitHub Actions.',
    date: '2024-01-25',
    readTime: '7 min read',
    slug: 'ci-cd-pipelines-with-github-actions',
  },

  // --- Arch Linux Blogs ---
  {
    title: 'Getting Started with Arch Linux',
    excerpt: 'A beginner’s guide to installing and setting up Arch Linux from scratch.',
    date: '2024-01-20',
    readTime: '10 min read',
    slug: 'getting-started-with-arch-linux',
  },
  {
    title: 'Arch Linux Package Management with Pacman',
    excerpt: 'Learn how to install, update, and manage packages using Pacman.',
    date: '2024-01-18',
    readTime: '8 min read',
    slug: 'arch-linux-package-management-with-pacman',
  },
  {
    title: 'Customizing Arch Linux with Hyprland',
    excerpt: 'Step-by-step guide to setting up a modern Hyprland desktop on Arch Linux.',
    date: '2024-01-15',
    readTime: '12 min read',
    slug: 'customizing-arch-linux-with-hyprland',
  },
  {
    title: 'Optimizing Arch Linux for Development',
    excerpt: 'Tips to configure Arch Linux for Full-Stack, AI/ML, and programming workflow.',
    date: '2024-01-12',
    readTime: '9 min read',
    slug: 'optimizing-arch-linux-for-development',
  },
  {
    title: 'Arch Linux Security Best Practices',
    excerpt: 'Learn how to secure your Arch Linux system with firewalls, users, and updates.',
    date: '2024-01-10',
    readTime: '8 min read',
    slug: 'arch-linux-security-best-practices',
  },
  {
    title: 'Arch Linux Terminal Tricks',
    excerpt: 'Powerful terminal commands and shortcuts to improve productivity in Arch Linux.',
    date: '2024-01-08',
    readTime: '7 min read',
    slug: 'arch-linux-terminal-tricks',
  },
];
