import { Project } from "@/types";

export const projects: Project[] = [
  // ===================== Full-Stack Projects (Coming Soon) =====================
  {
    title: 'Hotel Booking App',
    description: 'A full-stack hotel booking platform with user authentication, room management, and booking features.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Mountain Mirage Hotel',
    description: 'A hotel management web application for Mountain Mirage Hotel with reservations and admin dashboard.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Instagram Clone',
    description: 'A social media platform clone with photo sharing, stories, and user interactions.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Twitter Clone',
    description: 'A microblogging platform clone supporting tweets, followers, and notifications.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'LinkedIn Clone',
    description: 'A professional networking platform clone with profiles, connections, and job postings.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'WhatsApp Clone',
    description: 'A chat application clone with real-time messaging and notifications.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'AxionBank Dashboard',
    description: 'A banking dashboard application with account management, analytics, and transaction features.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Food Delivery App',
    description: 'A full-stack food delivery platform with restaurants, orders, and real-time tracking.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Tunify App',
    description: 'A music streaming full-stack application with playlists, search, and recommendations.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'BellyBuzz',
    description: 'A MERN stack food-based application with restaurants, orders, and reviews.',
    technologies: ['MongoDB', 'Express', 'React', 'Node.js', 'Tailwind CSS', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },
  {
    title: 'Zomato Clone',
    description: 'A clone of Zomato for restaurant discovery, food orders, and ratings.',
    technologies: ['Spring Boot', 'React', 'Tailwind CSS', 'PostgreSQL', 'AWS'],
    githubLink: '',
    demoLink: '',
    Image: '/projects/coming-soon.png',
  },

  // ===================== Java Swing / AWT Projects =====================
  {
    title: 'Floppy Birds',
    description: 'A Java desktop game inspired by Flappy Bird. Developed using Java Swing and AWT.',
    technologies: ['Java', 'Swing', 'AWT'],
    githubLink: 'https://github.com/yourusername/floppy-birds',
    demoLink: 'https://demo.com/floppy-birds',
    Image: '/projects/birds.png',
  },
  {
    title: 'Google Dinosaur Game',
    description: 'A clone of the famous Google Chrome Dinosaur Game. Built using Java Swing and AWT.',
    technologies: ['Java', 'Swing', 'AWT'],
    githubLink: 'https://github.com/yourusername/google-dinosaur',
    demoLink: 'https://demo.com/google-dinosaur',
    Image: '/projects/dinosaur.png',
  },
  {
    title: 'Space Invaders',
    description: 'A classic Space Invaders style desktop game built with Java Swing and AWT.',
    technologies: ['Java', 'Swing', 'AWT'],
    githubLink: 'https://github.com/yourusername/space-invaders',
    demoLink: 'https://demo.com/space-invaders',
    Image: '/projects/space.png',
  },
];
